server:
  port: 8765
spring:
  application:
    name: coinapp-apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: coin-app
        uri: lb://coin-app
        predicates: 
        - Path=/coin-app/**